(() => {
 const pages=[...document.querySelectorAll('.page')], step=document.querySelector('#step'), progress=document.querySelector('#progress'), toast=document.querySelector('#toast');
 let current=0, selectedDay='', selectedTime='', noTries=0, toastTimer;
 const noBtn=document.querySelector('#noBtn'), noHint=document.querySelector('#noHint');
 function showToast(msg){toast.textContent=msg;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),1600)}
 function hearts(x,y,count=7){const symbols=['♡','♥','✦','✧'];for(let i=0;i<count;i++){const el=document.createElement('i');el.className='heart-pop';el.textContent=symbols[Math.random()*symbols.length|0];el.style.left=(x+(Math.random()-.5)*80)+'px';el.style.top=(y+(Math.random()-.5)*24)+'px';el.style.animationDelay=(Math.random()*.15)+'s';document.body.append(el);setTimeout(()=>el.remove(),900)}}
 function go(n){pages[current].classList.remove('active');current=n;pages[current].classList.add('active');step.textContent=`0${n+1} / 05`;progress.style.width=((n+1)*20)+'%';if(n===3){document.querySelector('#chosenDay').textContent=selectedDay;document.querySelector('#chosenTime').textContent=selectedTime}if(n===4){document.querySelector('#finalDate').textContent=`${selectedDay} · ${selectedTime}`;const r=document.querySelector('.see-you').getBoundingClientRect();hearts(r.left+r.width/2,r.top+r.height/2,13)}}
 document.querySelector('#yesBtn').addEventListener('click',e=>{hearts(e.clientX,e.clientY,10);showToast('Yay! Кофены төлөвлөгөө эхэллээ ☕');setTimeout(()=>go(1),280)});
 function moveNo(){if(noTries>=4)return;noTries++;const r=noBtn.getBoundingClientRect(),pad=14;const x=pad+Math.random()*Math.max(1,innerWidth-r.width-pad*2),y=pad+Math.random()*Math.max(1,innerHeight-r.height-pad*2);noBtn.classList.add('escape');noBtn.style.left=x+'px';noBtn.style.top=y+'px';noBtn.style.transform=`rotate(${Math.random()*14-7}deg)`;noHint.textContent=['Өө, бараг баригдлаа! 😳','Хөөе, ганц кофе шүү дээ ☕','Ингээд л зугтаад байх уу? 😂','За за, “Үгүй” амралтаа авлаа ♡'][noTries-1];if(noTries===4){noBtn.textContent='За тэгье ♡';noBtn.classList.remove('no');noBtn.classList.add('yes');noBtn.classList.remove('escape');noBtn.style.left=noBtn.style.top=noBtn.style.transform='';noBtn.onclick=()=>go(1);noHint.textContent='за, ингээд кофе уухаар боллоо ♡';showToast('Би мэдэж байсан юм аа 😌')}}
 noBtn.addEventListener('click',moveNo);noBtn.addEventListener('pointerenter',e=>{if(e.pointerType==='mouse'&&noTries<4)moveNo()});
 document.querySelectorAll('.day-card').forEach(card=>card.addEventListener('click',()=>{selectedDay=card.dataset.day;document.querySelectorAll('.day-card').forEach(c=>{c.classList.toggle('selected',c===card);c.setAttribute('aria-pressed',String(c===card))});pages[1].querySelector('.next').disabled=false;const r=card.getBoundingClientRect();hearts(r.left+r.width/2,r.top+25,4)}));
 document.querySelectorAll('.time-card').forEach(card=>card.addEventListener('click',()=>{selectedTime=card.dataset.time;document.querySelectorAll('.time-card').forEach(c=>{c.classList.toggle('selected',c===card);c.setAttribute('aria-pressed',String(c===card))});pages[2].querySelector('.next').disabled=false;const r=card.getBoundingClientRect();hearts(r.left+r.width/2,r.top+10,4)}));
 pages[1].querySelector('.next').addEventListener('click',()=>selectedDay&&go(2));pages[2].querySelector('.next').addEventListener('click',()=>selectedTime&&go(3));
 document.querySelectorAll('[data-back]').forEach(btn=>btn.addEventListener('click',()=>go(Math.max(0,current-1))));
 document.querySelector('#confirmBtn').addEventListener('click',e=>{hearts(e.clientX,e.clientY,12);showToast('Товлогдлоо! See you soon ♡');setTimeout(()=>go(4),450)});
 document.querySelector('#restartBtn').addEventListener('click',()=>{selectedDay='';selectedTime='';noTries=0;noBtn.textContent='Үгүй';noBtn.className='btn no';noBtn.removeAttribute('style');noBtn.onclick=null;noHint.textContent='нэг кофе л шүү дээ… 👀';document.querySelectorAll('.day-card,.time-card').forEach(c=>{c.classList.remove('selected');c.setAttribute('aria-pressed','false')});document.querySelectorAll('.next').forEach(b=>b.disabled=true);go(0)});
 progress.style.width='20%';
})();